version: "3.1"
services:
  mongodb:
    image : mongo
    container_name: mongo_bilge
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${mongo_root}"
      MONGO_INITDB_ROOT_PASSWORD: "${mongo_creds}"
    volumes:
      - /home/barry/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${mongo_root}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${mongo_creds}"
      ME_CONFIG_MONGODB_URL: "mongodb://${mongo_root}:${mongo_creds}@mongo_bilge:27017/"
