version: "3.7"
# Bilge version .001
services:
  mongodb:
    image: bitnami/mongodb:latest
    container_name: ${mongo_container}
    environment:
      - MONGODB_ROOT_USERNAME=root
      - MONGODB_ROOT_PASSWORD=${mongo_creds}
      - MONGODB_USERNAME=${tankuser}
      - MONGODB_PASSWORD=${tankcreds}
      - MONGODB_DATABASE=bilge
    volumes:
      - /home/guru/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    
  smb:
    image: local:bilge_smb
    build: ./docker/services/smb/
    container_name: smb
    environment:
      - SMB_USERNAME=${SMB_USERNAME}
      - SMB_PASSWORD=${SMB_PASSWORD}
    volumes:
      - /home/guru/smb:/data/smb
    ports:
      - 445:445
    restart: unless-stopped

