FROM debian:bullseye-slim

ENV VIRTUAL_ENV=/fastapi/bin
ENV PATH="${VIRTUAL_ENV}/bin:$PATH"
COPY entrypoint.sh smb.conf /
COPY ./fastapi /fastapi

RUN apt-get update \
    && apt-get install -y \
    samba 
#g++ \
#python3 \
#python3-pip \
#python3-venv \
#&& apt-get clean \
#&& mkdir -p /data/db /data/smb \
#&& python3 -m venv $VIRTUAL_ENV \
#&& pip install -r ${VIRTUAL_ENV}/requirements.txt

EXPOSE 445/tcp

ENTRYPOINT ["/entrypoint.sh"]
CMD ["smbd"]
